version: '3'

services:
  dms:
    build: ./
    image: ens_backend:latest
    ports:
      - 5007:5000
    
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s

