apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekV5TWpBeApOVFU0TURsYUZ3MDBNekV5TWpBeE5UVTRNRGxhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEWVJuOTRYZnRhU3lHRlJrSzRZMXNPcGdLMkQ0a2NzWWlLVGE2TnpScGEyczZwMkpJagpEVVVGUUJsZXRTckRrdk1NMDhpdUl3RDlJS2hibCtLaHQvUDFNUnRlVjYrZVZ1QXFhcUdTKzc2Qk5yTnpOc0NRCjlyU1EzKzVrZ0w2dUZYY2xUNUVjZWt5TnFoc3RaVk1QbVRMU3FxYnNYUWNaWWl4Y1BkcjUvZll3TjVCVFIxQTAKVCs0SHhxSzRqQ2doMkp5bEdwbXM1cUlDMjk3dVlqdTVvcUZ4bDFnYUxHdmg3VU1hVjE3YTBzVTlscE9SMDFRLwpWN0ZUYU1TSGgrN1YrcURmaU9EQkJXaW5BczRaaUxKUzBCNVErVUxTaFNoNi85MkE5U3puaEhuOEhtQUgvRzRVClRBbzlUL2lGa1gwYit0c0F6dEUvNEI5ejhoQlFmSWFiMUx5cEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRJc0RNSktPcU9nZHE4Wjg0cApRaDg3Qzc4TGV6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFtVHVoRVFrTi9rRStsVkhyNGg4dldZNmpicjVhCmhaSnU0L1NNdFF2aHBvU0x0Ti9hVnNNYjFFTmF2aEx0elMzcXBBRU1pMHJYMGExMXZabkw5MEMyNHF2clZtOS8KMUJrL2xSNTdnTzdRNFhrZkVjRXJEQTFJVUlIS1hKSlpnd01ocUl5SUpOZjdtS3ZZYmtQc3pFbTBCSWtncnF4VgozM05KN083QTZvQml2c3lMdWVqN0k3Rzc0Y09pNDZxYVVkRXpCNGpYKzlEbWVVY3BGM25QalhrUXphV2I0U01UCkJLNndwVCtrWVc2cGI5Zm01aWdKa3JtZnVZS09vL2xqYmhtNW4wYjBZWVZ1dWZKazBrc1k5MzN1aU9JT21mQ2QKbEhaZ0ZBT2RiU2dxYldQczRqb0t6cGdGY1RmV2c0TDNWYzdrUlAyN3RMVVlOMkQ4UWZ6eDc5bE1FQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://b6b04c5b-6f9f-4706-a7a2-9b6d92fb8f66.k8s.ondigitalocean.com
  name: do-blr1-k8s-1-28-2-do-0-blr1-1703087737056
contexts:
- context:
    cluster: do-blr1-k8s-1-28-2-do-0-blr1-1703087737056
    user: do-blr1-k8s-1-28-2-do-0-blr1-1703087737056-admin
  name: do-blr1-k8s-1-28-2-do-0-blr1-1703087737056
current-context: do-blr1-k8s-1-28-2-do-0-blr1-1703087737056
kind: Config
preferences: {}
users:
- name: do-blr1-k8s-1-28-2-do-0-blr1-1703087737056-admin
  user:
    token: dop_v1_c65bbcf7dcaeed5e0048b7dd74030f7d035555614737a287a6cb3a8dbe64908a
