name: Deploy Images to GHCR


on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        # permissions:
        #   packages: write
        defaults:
          run:
            working-directory: './'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Echo GitHub Actor'
            run: echo aon-soft


          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: aon-soft
              password: ${{secrets.ACCESS_TOKEN}} 

          - name: 'Build And Push Image'
            run: |
              docker build . --tag ghcr.io/aon-soft/ens_backend:latest
              docker push ghcr.io/aon-soft/ens_backend:latest


      restart-deployment:
        needs: build-and-push
        runs-on: ubuntu-latest
        steps:
          - name: Set up kubectl
            uses: digitalocean/action-doctl@v2
            with:
              token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
              k8s-configuration-file: ./k8s/kubeconfig.yml

          - name: Trigger Kubernetes Deployment Restart
            run: |
              kubectl rollout restart deployment ens-server-depl